# Carsten Lenz
# 2023/03/07
#

apiVersion: v1
kind: Secret
metadata:
  name: avp-demo-kustomize-secret1
stringData:
  foo: <path:product-team-example/data/hello#foo>
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "product-team-example/data/hello"
  name: avp-demo-kustomize-secret2
stringData:
  foo: <foo>
