---
# Carsten Lenz
# 2023/03/07
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret1
stringData:
  foo: "{{ .Values.secrets.path | default (randAlphaNum 8) }}"
---
# Carsten Lenz
# 2023/03/07
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "{{ .Values.secrets.annotated }}"
  name: {{ .Chart.Name }}-secret2
stringData:
  foo: "<foo>"
