# Carsten Lenz
# 2023/03/07
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp-demo-helm4
spec:
  destination:
    namespace: product-team-example
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/carslen/avp-demo'
    targetRevision: HEAD
    path: charts/avp-demo4
    plugin:
      env:
        - name: HELM_ARGS
          value: "-f values-demo.yaml"
  project: project-example
  syncPolicy:
    automated: { }
