# Carsten Lenz
# 2023/03/07
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp-demo-helm3
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: product-team-example
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://carslen.github.io/avp-demo'
    targetRevision: 0.1.0
    chart: avp-demo3
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            mariadb:
                auth:
                database: foo<path:product-team-example/data/hello#foo>
                username: "foo"
              commonLabels:
                foo: "<path:product-team-example/data/hello#foo>"
            secrets:
              path: <path:product-team-example/data/hello#foo>
              annotated: "product-team-example/data/hello"
  project: project-example
  syncPolicy:
    automated: { }
