secrets:
  path: <path:product-team-example/data/hello#foo>

mariadb:
  auth:
    database: foo4<path:product-team-example/data/hello#foo>
    username: lala
  commonLabels:
    foo: <path:product-team-example/data/hello#foo>
